### ISSUE TITLE
Geen alt!

### ISSUE THREAD

**Issue by TimOosterveer** [Sascha-davidson/the-startup-responsive-interactieve-website#3]
https://github.com/Sascha-davidson/the-startup-responsive-interactieve-website/blob/c069631814febb9949f18c64d586140eb82cdbe0/mobile-first-demo/idee-2.html#L84

**Comment by Sascha-Davidson** [comment]
Deze heb ik vervangen voor een svg en als je de `alt=""` doet dan geef je aan dat de screen reader het mag overslaan. dit de ik omdat het plaatje niet belangrijk is voor mensen met een screenreader.
